# CMake generated Testfile for 
# Source directory: /Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/src/internet-apps/examples
# Build directory: /Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/cmake-cache/src/internet-apps/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dhcp-example "ns3.37-dhcp-example-default")
set_tests_properties(ctest-dhcp-example PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/src/internet-apps/examples/CMakeLists.txt;1;build_lib_example;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-traceroute-example "ns3.37-traceroute-example-default")
set_tests_properties(ctest-traceroute-example PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/src/internet-apps/examples/CMakeLists.txt;12;build_lib_example;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/src/internet-apps/examples/CMakeLists.txt;0;")
