# CMake generated Testfile for 
# Source directory: /Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch
# Build directory: /Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_basic-tp-trace "ns3.37-basic-tp-trace-debug")
set_tests_properties(ctest-scratch_basic-tp-trace PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_myfirst "ns3.37-myfirst-debug")
set_tests_properties(ctest-scratch_myfirst PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_mysecond "ns3.37-mysecond-debug")
set_tests_properties(ctest-scratch_mysecond PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_mythird "ns3.37-mythird-debug")
set_tests_properties(ctest-scratch_mythird PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_nms-project "ns3.37-nms-project-debug")
set_tests_properties(ctest-scratch_nms-project PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.37-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_nms-experiments_nms-project "ns3.37-nms-project-debug")
set_tests_properties(ctest-scratch_nms-experiments_nms-project PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/nms-experiments/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.37-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build/scratch/subdir/" _BACKTRACE_TRIPLES "/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/Users/anirudhsriram/Downloads/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
